'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Alarm
    Public Property ID As Integer
    Public Property Severity As String
    Public Property Node As String
    Public Property Event_Time As Nullable(Of Date)
    Public Property Fault As String
    Public Property Description As String
    Public Property Comment As String
    Public Property Status As String
    Public Property UnitID As Nullable(Of Short)
    Public Property Owner As String
    Public Property Week As Nullable(Of Byte)
    Public Property Year As Nullable(Of Short)
    Public Property Update_date As Nullable(Of Date)
    Public Property Ticket As String
    Public Property Modifies As String
    Public Property Updated_By As String

    Public Overridable Property Unit As Unit
    Public Overridable Property Unit1 As Unit

End Class
