'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Data.Entity
Imports System.Data.Entity.Infrastructure

Partial Public Class ssportaldbEntities1
    Inherits DbContext

    Public Sub New()
        MyBase.New("name=ssportaldbEntities1")
    End Sub

    Protected Overrides Sub OnModelCreating(modelBuilder As DbModelBuilder)
        Throw New UnintentionalCodeFirstException()
    End Sub

    Public Overridable Property Alarms() As DbSet(Of Alarm)
    Public Overridable Property Nodes() As DbSet(Of Node)
    Public Overridable Property Units() As DbSet(Of Unit)
    Public Overridable Property Users() As DbSet(Of User)
    Public Overridable Property Ploads() As DbSet(Of Pload)

End Class
