'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Pload
    Public Property Id As Long
    Public Property Sample_Time As Nullable(Of Date)
    Public Property MBC_Prefix As String
    Public Property MBC_Name As String
    Public Property Pload_Avg As Nullable(Of Decimal)
    Public Property Pload_Max As Nullable(Of Decimal)
    Public Property Pload_Max_Bladeid As Nullable(Of Short)

End Class
