'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic
Imports System.ComponentModel.DataAnnotations

Partial Public Class User
    <Key>
    Public Property Name As String
    Public Property Region As String
    Public Property Role As String
    Public Property Alternate As String
    Public Property Full_Name As String
    Public Property Unit As String
    Public Property Sub_Unit As String
    Public Property Unit_Supervised As String
    Public Property Sub_Unit_Supervised As String
    Public Property Location As String
    Public Property Last_Logon As String
    Public Property Authentication As String
    Public Property Code As String

End Class
